#!/bin/tcsh 
#***********************************************************************
#     
#    Copyright (c) 2012, Lawrence Livermore National Security, LLC.
#                        Produced at the Lawrence Livermore National
#                        Laboratory.
#                        Written by Ian Thompson, I-Thompson@llnl.gov
#     
#    LLNL-CODE-XXXXX All rights reserved.
#
#    Copyright 2012, I.J. Thompson
#     
#    This file is part of FRESCO.
#
#    FRESCO is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#     
#    FRESCO is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#     
#    You should have received a copy of the GNU General Public License
#    along with FRESCO. If not, see <http://www.gnu.org/licenses/>.
#     
#    OUR NOTICE AND TERMS AND CONDITIONS OF THE GNU GENERAL PUBLIC
#    LICENSE
#     
#    Our Preamble Notice
#
#      A. This notice is required to be provided under our contract
#         with the U.S. Department of Energy (DOE). This work was
#         produced at the Lawrence Livermore National Laboratory under
#         Contract No. DE-AC52-07NA27344 with the DOE.
#      B. Neither the United States Government nor Lawrence Livermore
#         National Security, LLC nor any of their employees, makes any
#         warranty, express or implied, or assumes any liability or
#         responsibility for the accuracy, completeness, or usefulness
#         of any information, apparatus, product, or process disclosed,
#         or represents that its use would not infringe privately-owned
#         rights.
#      C. Also, reference herein to any specific commercial products,
#         process, or services by trade name, trademark, manufacturer
#         or otherwise does not necessarily constitute or imply its
#         endorsement, recommendation, or favoring by the United States
#         Government or Lawrence Livermore National Security, LLC. The
#         views and opinions of authors expressed herein do not
#         necessarily state or reflect those of the United States
#         Government or Lawrence Livermore National Security, LLC, and
#         shall not be used for advertising or product endorsement
#         purposes.
#        
#    The precise terms and conditions for copying, distribution and
#    modification are contained in the file COPYING.
#        
#***********************************************************************

#
# Usage   
# 	mk 			 : first compiler for your ARCH
# 	mk <compiler> 		 : use this compiler
# 	mk <compiler> <options>  

set COMP = 'f90'
set PREF='a'
# change to any local preferences: 
#  copy & edit these lines yourself

if(! $?ARCH && -X arch) setenv ARCH `arch`
if( ${ARCH} == 'x86_64' ) then   
      if( -X g95 )     set COMP = 'g95'
      if( -X pgf90 )   set COMP = 'pgf90'
      if( -X pathf95 ) set COMP = 'pathf95'
      if( -X f90 ) 	set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i686' ) then 	# Linux Intel
      if( -X g95 )     set COMP = 'g95'
      if( -X pgf90 )   set COMP = 'pgf90'
      if( -X pathf95 ) set COMP = 'pathf95'
      if( -X ifort )   set COMP = 'ifort'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'ia64' ) then    # Linux Itanium
      if( -X ifort )   set COMP = 'ifort'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'ppc' ) then 	# Mac Powerpc
      if( -X g95 )     set COMP = 'g95'
      if( -X xlf )     set COMP = 'xlf'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i386' ) then 	# Mac Intel
      if( -X gfortran )     set COMP = 'gfortran'
      if( -X ifort )   set COMP = 'ifort'
      if( -X f95 )     set COMP = 'f95'
      if( -X g95-0.93 )     set COMP = 'g95-0.93'
      if( -X g95 )     set COMP = 'g95'
#      if( -X pgf90 )   set COMP = 'pgf90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'sun4' || ${ARCH} == 'sun4u' ) then 	# Sun sparc
      if( -X f90 )     set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'i86pc' ) then 	# Sun opterons
      if( -X f90 )     set COMP = 'f90'
      set PREF=${ARCH}
endif
if( ${ARCH} == 'pwr5' ) then    # uP
      if( -X xlf90 )     set COMP = 'xlf90'
      set PREF=${ARCH}
endif
echo From arch=${ARCH}, expect compiler ${COMP}

 if ($#argv != 0)  then
 set try=$1
#if (-X ${try} && ${try} != 'fresco' && ${try} != 'sfresco' && ${try} != 'install' && ${try} !~ '-.*')  then
 if (-X ${try} && ${try} != 'fresco' && ${try} != 'sfresco' && ${try} != 'install' ) then
	set COMP = $try
	shift
 endif
 endif
set DIR = ${PREF}-${COMP}

if( ! -e ${DIR}) mkdir ${DIR}
echo Choose compiler ${COMP} in directory ${DIR}
chdir ${DIR}
echo ln -s ../*.f . >& /dev/null
ln -s ../*.f . >& /dev/null
echo \cp -f ../makefile . 
\cp -f ../makefile . 
echo make ${argv}  FC=${COMP}
# if(#{COMP} == gfortran )  then   set COMP = 'gfortran -Wtabs'  endif

make ${argv} FC=${COMP}
